[workspace]
channels    = ["conda-forge"]
name        = "nimvault"
platforms   = ["linux-64"]
version     = "0.1.0"

[dependencies]
nim = ">=2.0.0,<3"

[tasks]
build = "nimble build -y"
test  = "nimble test -y"

[feature.docs.dependencies]
emacs  = ">=30.2,<31"
pandoc = ">=3.9,<4"

[feature.docs.pypi-dependencies]
shibuya        = ">=2025.12.13, <2026"
sphinx         = ">=9.0.4, <10"
sphinx-sitemap = ">=2.9.0, <3"

[feature.docs.tasks]
mkrst     = {cmd = "emacs --batch --load export.el", cwd = "docs"}
sphinxbld = {cmd = "sphinx-build docs/source/ docs/build", depends-on = ["mkrst"]}
nimdoc    = {cmd = "nim doc --project --index:on --outdir:docs/build/apidoc src/nimvault.nim"}
docbld    = {depends-on = ["sphinxbld", "nimdoc"]}
docdel    = {cmd = "rm -rf build source/*.rst", cwd = "docs"}

[environments]
docs = {features = ["docs"]}
