[workspace]
channels = ["conda-forge"]
name = "nimvault"
platforms = ["linux-64"]
version = "0.2.0"

[dependencies]
nim = ">=2.0.0,<3"

[tasks]
build = "nimble build -y"
test = "nimble test -y"
install = "nimble build -y -d:release && install -Dm755 bin/nimvault ~/.local/bin/nimvault"

[feature.docs.dependencies]
python = ">=3.12,<4"
emacs = ">=30.2,<31"
graphviz = ">=12,<13"
pandoc = ">=3.9,<4"

[feature.docs.pypi-dependencies]
shibuya = ">=2025.12.13, <2026"
sphinx = ">=9.0.4, <10"
sphinx-sitemap = ">=2.9.0, <3"

[feature.docs.tasks]
mkrst = { cmd = "emacs --batch --load export.el", cwd = "docs" }
sphinxbld = { cmd = "sphinx-build docs/source/ docs/build", depends-on = [
  "mkrst",
] }
nimdoc = { cmd = "nim doc --project --index:on --outdir:docs/build/apidoc src/nimvault.nim" }
docbld = { depends-on = ["sphinxbld", "nimdoc"] }
docdel = { cmd = "rm -rf build source/*.rst", cwd = "docs" }

[environments]
docs = { features = ["docs"] }
