name: Build and Deploy Documentation

concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: >-
            docs

      - uses: iffy/install-nim@v5
        with:
          version: "2.2.x"

      - name: Install cligen
        run: nimble install cligen -y

      - name: Generate Docs
        run: pixi run -e docs docbld

      - name: Build Nim API docs
        run: pixi run nimdoc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          cname: nimvault.rgoswami.me
